### ISSUE TITLE
Ошибка в примере про контейнер zoo

### ISSUE THREAD

**Issue by str-anger** [SerVB/ami-prog-cpp#1]
Вот такой код
```
    Cat c;
    Dog d;

    vector<Mammal> zoo;
    zoo.push_back(c);
    zoo.push_back(d);

    cout << zoo[0].voice();
```
выведет на экран "Not implemented yet", поскольку при размещении в контейнере объекты классов-наследников потеряют и собственные поля, и таблицу виртуальных методов (условно, им отрубают руки-ноги, чтобы они стали обычными Mammal). Это происходит потому, что в векторе под каждого Mammal выделено ровно size(Mammal) памяти, и они уже зарезервированы - ничего больше туда влезть не сможет. Это же случится при Mammal x = Dog(); Они останутся просто экземплярами Mammal с тем лишь отличием, что были проинициализированы конструкторами своих классов. Ожидаемое поведение с мяуканием можно получить, сделав контейнер указателей:

```
    vector<Mammal*> zoo2;
    zoo2.push_back(&c);
    zoo2.push_back(&d);
    cout << zoo2[0]->voice() << endl;
```

**Comment by SerVB** [comment]
@str-anger , благодарю за замечание, всегда готов принимать предложения по улучшению конспектов! Исправлю с добавлением следующей лекции, если Вы не сделаете Pull Request до этого.

**Comment by SerVB** [comment]
Ошибка исправлена.
